### PR TITLE
Add `tools` install & manage support

### PR DESCRIPTION
**Pull request by mrxiaozhuox**
- Supported install tool.
- Supported custom html.

### CODE REVIEW

**Review by jkelleyrtp — CHANGES_REQUESTED** [review]
Waiting on the bug fix as per discord :)

**Comment by mrxiaozhuox** [comment]
> Waiting on the bug fix as per discord :)

It's been fixed

**Comment by mrxiaozhuox** [comment]
@jkelleyrtp please review my PR 😢

**Comment by jkelleyrtp** [comment]
Looks good - will follow this up with some grammar adjustments before making a new release. Excited for wasm-opt!

**Pull request merged**
