### PR TITLE
[TOOL] Adding tailwind-css

### PR DESCRIPTION
**Pull request by bamboo-maker**
Added support for tailwind-css as a tool.
Adding  release profile handling for tailwind-css by minifying the bundle.
Added the option "-Oz" in release profile for wasm-opt.
Fixed typo in src/config.rs.
Updated docs in configure.md.
Updated Dioxus.toml by adding tailwind tool.

### CODE REVIEW

**Comment by bamboo-maker** [comment]
Noobie to Rust so there is probably some horrifying things

**Comment by mrxiaozhuox** [comment]
I think use `tailwindcss` is better than `tailwind-css` 😄

**Comment by bamboo-maker** [comment]
Yeah sure ill change that :). Also I did not test on mac or windows .
Also I was not sure if I had to create a tailwind directory in the tool directory or just put the binary as-is

**Comment by mrxiaozhuox** [comment]
> Also I was not sure if I had to create a tailwind directory in the tool directory or just put the binary as-is

create a new dir please:

image

**Comment by bamboo-maker** [comment]
It is already the case 😉

**Comment by bamboo-maker** [comment]
Pushed the typo fix

**Comment by mrxiaozhuox** [comment]
Have you tested it?

**Review by mrxiaozhuox — APPROVED** [review]

**Comment by mrxiaozhuox** [comment]
thank you!

**Comment by bamboo-maker** [comment]
> Have you tested it?

Yep, it works !



> thank you!

My pleasure ! Looking forward to contribute on the main crate !

**Pull request merged**
